### PR TITLE
Fix the ice not melting after winter has ended due to AbstractBlockMixin.checkIfMeltableAdded being called when a player does not manually place a block. Use a mixin from Block.onPlaced instead.

### PR DESCRIPTION
**Pull request by NathanSaidas**
Hello, I encountered the issue of "Ice not melting" when winter is over. While running fabric-seasons only I can observe that ice does actually melt when winter is over. The issue seems more apparent when integrated with other mods. One such mod I observed the issue with was Snow! Real Magic! (https://www.curseforge.com/minecraft/mc-mods/snow-real-magic-fabric).

After doing some debugging and adding diagnostics it seems like the sole thing preventing ice from melting is that it was placed "manually". However in my experience the ice is not placed manually it's placed procedurally by using ServerWorld.setBlockState (net.minecraft.class_1937.method_8501). This method will indirectly call BlockState.onBlockAdded which is what the current AbstractBlockMixin targets.

I think an alternative is to use a mixin for Block.onPlaced which appears to be called when a LivingEntity places a block. I'm not entirely sure what the reasoning was to prevent manually placed blocks from melting under the conditions for this mod, but this change will respect those conditions while allowing "naturally" placed "Meltable" blocks to melt outside of winter when mods like Snow! Real Magic! use setBlockState.

Here is a diagnostic log I added to track what was causing this "manually" placed block on my server. 

[00:06:47] [Server thread/INFO]: [Fabric Seasons]] Place meltable translation{key='block.minecraft.ice', args=[]} <- translation{key='block.minecraft.water', args=[]}
[00:06:47] [Server thread/INFO]: 	at net.minecraft.class_4970.handler$gmj000$seasons$checkIfMeltableAdded(class_4970.java:5030)
[00:06:47] [Server thread/INFO]: 	at net.minecraft.class_4970.method_9615(class_4970.java:-1)
[00:06:47] [Server thread/INFO]: 	at net.minecraft.class_4970$class_4971.method_26182(class_4970.java:936)
[00:06:47] [Server thread/INFO]: 	at net.minecraft.class_2818.method_12010(class_2818.java:263)
[00:06:47] [Server thread/INFO]: 	at net.minecraft.class_1937.method_30092(class_1937.java:221)
[00:06:47] [Server thread/INFO]: 	at net.minecraft.class_1937.method_8652(class_1937.java:206)
[00:06:47] [Server thread/INFO]: 	at net.minecraft.class_1937.method_8501(class_1937.java:321)
[00:06:47] [Server thread/INFO]: 	at snownee.snow.WorldTickHandler.tick(WorldTickHandler.java:33)
[00:06:47] [Server thread/INFO]: 	at net.minecraft.class_3218.redirect$gom000$snowrealmagic$cancelVanillaSnow(class_3218.java:26714)
[00:06:47] [Server thread/INFO]: 	at net.minecraft.class_3218.method_18203(class_3218.java:460)
[00:06:47] [Server thread/INFO]: 	at net.minecraft.class_3215.method_14161(class_3215.java:379)
[00:06:47] [Server thread/INFO]: 	at net.minecraft.class_3215.method_12127(class_3215.java:323)
[00:06:47] [Server thread/INFO]: 	at net.minecraft.class_3218.method_18765(class_3218.java:319)
[00:06:47] [Server thread/INFO]: 	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:875)
[00:06:47] [Server thread/INFO]: 	at net.minecraft.class_3176.method_3813(class_3176.java:289)
[00:06:47] [Server thread/INFO]: 	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:819)
[00:06:47] [Server thread/INFO]: 	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:665)
[00:06:47] [Server thread/INFO]: 	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:257)
[00:06:47] [Server thread/INFO]: 	at java.lang.Thread.run(Thread.java:833)

### CODE REVIEW

**Comment by NathanSaidas** [comment]
Note: there are handful of issues raised about this that I think this change will solve.

https://github.com/lucaargolo/fabric-seasons/issues/146 
https://github.com/lucaargolo/fabric-seasons/issues/138
https://github.com/lucaargolo/fabric-seasons/issues/136
https://github.com/lucaargolo/fabric-seasons/issues/133

**Comment by GodsTitan** [comment]
Thanks for taking your time to fix it :) will this fix be coming to 1.19.2 or only 1.20?

**Comment by NathanSaidas** [comment]
This was targeting 1.19.2, I'm not as familiar with 1.20 yet but it could be a similar issue and could possibly be merged there as well. I will await the developers comments.

**Comment by FeeeeK** [comment]
Hi, if it's not too much trouble, could you please take a look at #141? That issue is also related to `Snow! Real! Magic!", but I have not been able to debug the cause of its occurrence

**Comment by spv420** [comment]
lgtm, this is a much better patch than mine

**Comment by plk01** [comment]
for me after do compile with that fix, ice starts melting properly is working briliant but now im stuck on season isnt passing anymore, only by manual command /season set * otherwise checks by /season query is showing that season is passing to same one 
edit : forget to mention im using better minecraft 1.19.2 fabric edition modpack
season query bug
 
second edit : what i found is that message showing from /season query is wrong, after half time in tick of season pass, /season query message is changing to right season and mod is working fine like mentioned, only problem is with that message showing wrong next season

**Comment by axd1x8a** [comment]
@plk01 wrong season in query command is a known bug, I'm already working on fix for it

**Pull request closed without merging**
